In [2]:
from numpy import *

a = array([[1,2,3,4],[5,6,7,8]])

print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# shape : It is used find the dimensional shape of the

array

print(a.shape)

(2, 4)


In [4]:
#ndim : returns an integer that tells us how many dimensions the array have 

print("ndim",a.ndim)

ndim 2


In [5]:
#size : return the size of the array

print("Size : ",a.size)

Size :  8


In [6]:
#dtype : return the datatype of the array

print("datatype : ",a.dtype)

datatype :  int32


In [7]:
#itemsize : The element size of this data-type object
print(a.itemsize)

4


In [8]:
#data :
print(a.data)

In [9]:
m1 = array([[1,2],[3,4]])

m2 = array([[5,6],[7,8]])

print(m1)

print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
#dot : return the multiplication of the matrix

mul = dot(m1,m2)

print(mul)

[[19 22]
 [43 50]]


In [11]:
#multiply : it only multiply the elements

mult = multiply(m1,m2) #only multiplication

print(mult)

[[ 5 12]
 [21 32]]


In [12]:
#subtract : will subtract the matrix

subtrac = subtract(m2,m1)
print(subtrac)

[[4 4]
 [4 4]]


In [13]:
#add : will add the two or more matrix

addM = add(m1,m2)

print(addM)

[[ 6  8]
 [10 12]]


In [14]:
b = array([4,5,56,7,8,9,12,45])

#starting from the 2nd element to the end

print(b[2:])

[56  7  8  9 12 45]


In [15]:
#starting from first element to the 2-1 element

print(b[:2])

[4 5]


In [16]:
c = array([1,2,3,4,5,6,7,8,9])
#reshape : shape the array according to our choice

print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#max = maximum element from the array

print(c.max())

9


In [18]:
#min : minimum element from the array

print(c.min())

1


In [19]:
#axis=1 means row wise maximum

re = c.reshape(3,3)

print("Max in row is : ",re.max(axis=1))

Max in row is :  [3 6 9]


In [20]:
#axis=0 means column wise minimum

print("Min in row is : ",re.min(axis=0))

Min in row is :  [1 2 3]


In [21]:
m4 = array([4,9,25])

#sqrt : square root of the elements

print(sqrt(m4))

[2. 3. 5.]


In [23]:
#std : calculates the standard deviation of given data along a specified axis.

print("Standard deviation : ",std(m4))

Standard deviation :  8.9566858950296


In [24]:
#vstack : arrange the array vertically

print(vstack((m1,m2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
#hstack : arrange the array horizontally

print(hstack((m1,m2)))

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
#arange : starting to 0 to 20 range with 2 gap

print(arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
#same as arange but default in float

print(linspace(0,20,5))

[ 0.  5. 10. 15. 20.]


In [29]:
#horizontal split 
a = array([1,2,3,4,5,6,7,8])

hnew = hsplit(a,2)

print(hnew)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
